{% set name = "python_http_client" %}
{% set version = "3.3.7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/sendgrid/{{ name.replace('_', '-') }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4b87ce2dbebae18e21453ac1b8c7ea31ef3139c94decc85ff5a07d4203671c56

build:
  skip: true  # [py<34]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

  {% set skip_tests = "" %}
  # Broken test: Compares current machine time with copyright notice's old year
  {% set skip_tests = skip_tests + " --deselect=tests/test_daterange.py::DateRangeTest::test__daterange" %}
  # Test is pointless for packaging, it only checks for presence of repo files (readme, etc).
  {% set skip_tests = skip_tests + " --deselect=tests/test_repofiles.py::RepoFiles::test_file_existence" %}

test:
  source_files:
    - tests
  requires:
    - python
    - pip
    - pytest
  imports:
    - python_http_client
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv {{ skip_tests }} tests

about:
  home: https://sendgrid.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twilio SendGrid's Python HTTP Client for calling APIs
  description: Quickly and easily access any RESTful or RESTful-like API
  doc_url: https://github.com/sendgrid/python-http-client
  dev_url: https://github.com/sendgrid/python-http-client

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
