travis:
  secure:
    BINSTAR_TOKEN: GAqLAoy2A4A1C3mce9MxwPM0c1FfFv3DwjcBGGVNTEl1yEzK5w6lPtHDfFg3pyxhN3xfPR/X427zCzeYEPmGbwRiOODX4lWFloarzglLR1CTrhJN+oh1l0lvFwZBh+Aw33dvENTIohth14L/i5nicF/Gd4jlrJ/L1NEVPYOSTy4RnnoS5clDtnlTDf25FXQGY9dphSzfnXGIdin3UPJq8Uy1mpNN7wXD0bH8jCCYscSxolTz7yMLVm8DffLYryWlgbC8IJlHDJqi83TNcOi7SwPXUoxC53Fu5vbp3WiY5On3abH2xMK9aIc0rplVAHnF/pyur46ya4ZSE47i81FukewBQK3nVEtcBJVeJsfZuvVWIWP/EpHWLC6vMwj5GyEScflFoZaMCVZRMp5bq1PwGGI5a6+gJthnsuByk04SW2deHreRzFqOTUUkAg9NhrmqhBwteultzI02rMEh1e8T0zZDXJ54IQB79tLFT8rAANuSCdDKXm0ii94GqtzfyoxUb+un7OcvZxoj25+tzMMpfXNg04BHNR6tAqAr06DSzCHXY9OFbyPPTuqJAqr/fZz+6Ygdp6SOl+1zRN7y7oXz1xNYKDN4aq4P8yUOh58wPW101rNngUEKruMqNQcVq29anUrH+aN2Z5PTgg+DrysPk9OumL3sqwvVsPmk5DU+VsY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
