travis:
  secure:
    BINSTAR_TOKEN: mJsCqyUMEyHQ/PQP9O0dlv8+005ZUzjQ1lp7n0VKfnzZK9pHyFHWbE0njHdluZBE7m8tBO/Mh+ScACL/9OZJQUfIe4HYBsI3MN9/9c1KgvVImPFdpfh/caa9FYfab6YPFqxH9yJshjpipZHcBWKqapLNJtmvRHoMs6ylxDrSC3wiEDbrgq2gTBuZF8sPQhzqYSwRWrII+Dndi7uSB1HM1DfcwBvGaRNZ3FEWgSWQZTKTVRA/sijf9dzUajVbLodN/I0zTQw2GF2d/JIXrZegmrAs3aYLom0qWktbG+FB68vPTZ5lJaPwsYGLA8m38eW+wGgXRWGRI2BLO+qGlzYT6dklIsCxpiU5BgZXr+PBlZhlK2EL/lFYEqVWlHj2mQR3ntr7YiG8Bz4xvSF35x6op5Jy+a9F+j0n5T+mMvkHWds5TLJor4k11sxYVV9fXLoBjd9tHWfO0HwETxfp9eElLEicWxq+bHdzwRATcegWMamhbJKYHm4nT4JFMbUE0zb/NUn1zDNn0e08aepo5Rrfow9u0kJ63Y8T8mnKVBXWR8CqBg4JSQCpPY/+Vpzyvo9JOMoKh8iAD/JqUVffexFb8ARckEYL2O5UK7aR4auB9EltF2bosPcuvwU08daFAHAskp+rnTK9GsffnT3iWz4kJ/ZglLkLhPx4BlBoFQPXOec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
